import Head from "next/head";
// import styles from "../styles/Home.module.css";

// Imports:
import NavbarComponent from "../components/NavbarComponent";
import TopSelectorComponent from "../components/topSelector/TopSelectorComponent";

export default function Home(): JSX.Element {
    return (
        <div>
            <Head>
                <title>Create Next App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <NavbarComponent />

            <body className="main-container">
                <TopSelectorComponent />
            </body>

            <style jsx>{`
                .main-container {
                    display: flex;
                    flex-direction: column;
                    padding: 0 70px;
                    justify-content: center;
                }
            `}</style>
        </div>
    );
}
